patcher-args = "--striplibs=arm64-v8a"
release-cleanup = true

[YouTube]
package-name = "com.google.android.youtube"
app-source = "rjaakash/peachmeow-store"
patches-version = "pre-release"
cli-version = "pre-release"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"

[Music]
package-name = "com.google.android.apps.youtube.music"
app-source = "rjaakash/peachmeow-store"
patches-version = "pre-release"
cli-version = "pre-release"

["Photos De-ReVanced"]
package-name = "com.google.android.apps.photos"
app-name = "Photos"
app-source = "rjaakash/peachmeow-store"
patches-source = "RookieEnough/De-ReVanced"
morphe-brand = "De-ReVanced"
patcher-args = "-e 'Enable DCIM folders backup control'"

["Proton VPN hoo-dles"]
package-name = "ch.protonvpn.android"
app-name = "ProtonVPN"
app-version = "🐱"
app-source = "ProtonVPN/android-app"
patches-source = "hoo-dles/morphe-patches"
morphe-brand = "hoo-dles"
patcher-args = "-f"

[Reddit]
package-name = "com.reddit.frontpage"
app-source = "rjaakash/peachmeow-store"

["YouTube Anddea"]
package-name = "com.google.android.youtube"
app-name = "YouTube"
app-source = "rjaakash/peachmeow-store"
patches-source = "anddea/revanced-patches"
patches-version = "pre-release"
morphe-brand = "Anddea"
patcher-args = "-e 'Custom header for YouTube' -e 'MaterialYou' -e 'Theme' -e 'Custom Shorts action buttons' -OiconType=outline -e 'Custom branding icon for YouTube' -OappIcon=afn_blue -OrestoreOldSplashAnimation=true -e 'Overlay buttons' -OiconType=thin -e 'Settings for YouTube' -OrvxSettingsLabel=Anddea -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=rvx_letters_bold -OapplyToAll=false"

["Music Anddea"]
package-name = "com.google.android.apps.youtube.music"
app-name = "Music"
app-source = "rjaakash/peachmeow-store"
patches-source = "anddea/revanced-patches"
patches-version = "pre-release"
morphe-brand = "Anddea"
patcher-args = "-e 'Custom header for YouTube Music' -e 'Custom branding icon for YouTube Music' -OappIcon=afn_blue -OrestoreOldSplashIcon=true -e 'Settings for YouTube Music' -OrvxSettingsLabel=Anddea -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon=rvx_letters_bold -OapplyToAll=false"
