name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
    - cron: "30 10 * * *"

permissions:
  contents: write
  actions: write

jobs:
  resolver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: |
          set -e

          if [ "${{ github.repository }}" = "rjaakash/peachmeow" ]; then
            if [ -z "${{ secrets.PEACHMEOW_GITHUB_PAT }}" ]; then
              echo "PEACHMEOW_GITHUB_PAT is required in main repo"
              exit 1
            fi
            export GH_TOKEN="${{ secrets.PEACHMEOW_GITHUB_PAT }}"
          else
            export GH_TOKEN="${{ github.token }}"
          fi

          python3 resolver.py

          RUNS=$(gh run list --limit 200 --json databaseId -q '.[].databaseId')

          COUNT=0
          for ID in $RUNS; do
            COUNT=$((COUNT+1))
            if [ $COUNT -gt 10 ]; then
              gh run delete "$ID"
            fi
          done
